words <- c("I","am","Vijayan")
(paste(words, collapse = " "))
x <- rnorm(100,1:10)
myMean <- function(x) sum(x)/length(x)
myMean(x)
myVar <- function(x) sum((x- myMean(x))^2) / (length(x)-1)
myVar(1:100)
apropos("test")
objects()
remove(ind)
popUpData <- read.table(file.choose(), header = TRUE, sep = ",")
attach(popUpData)
hist(X)
hist(c(X,Y))
train <- read.csv(file.choose(), header = TRUE)
summary(train)
colnames(train)
